package com.example.newtrendingmoviesservice.gRPC;//
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gRPC.proto

public final class GRPC {
  private GRPC() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TopRatedRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TopRatedRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code TopRatedRequest}
   */
  public static final class TopRatedRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TopRatedRequest)
      TopRatedRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TopRatedRequest.newBuilder() to construct.
    private TopRatedRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TopRatedRequest() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new TopRatedRequest();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GRPC.internal_static_TopRatedRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GRPC.internal_static_TopRatedRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TopRatedRequest.class, Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TopRatedRequest)) {
        return super.equals(obj);
      }
      TopRatedRequest other = (TopRatedRequest) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TopRatedRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TopRatedRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TopRatedRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TopRatedRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TopRatedRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TopRatedRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TopRatedRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TopRatedRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TopRatedRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TopRatedRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TopRatedRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TopRatedRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TopRatedRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TopRatedRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TopRatedRequest)
        TopRatedRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GRPC.internal_static_TopRatedRequest_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GRPC.internal_static_TopRatedRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TopRatedRequest.class, Builder.class);
      }

      // Construct using GRPC.TopRatedRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GRPC.internal_static_TopRatedRequest_descriptor;
      }

      @Override
      public TopRatedRequest getDefaultInstanceForType() {
        return TopRatedRequest.getDefaultInstance();
      }

      @Override
      public TopRatedRequest build() {
        TopRatedRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public TopRatedRequest buildPartial() {
        TopRatedRequest result = new TopRatedRequest(this);
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TopRatedRequest) {
          return mergeFrom((TopRatedRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TopRatedRequest other) {
        if (other == TopRatedRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TopRatedRequest)
    }

    // @@protoc_insertion_point(class_scope:TopRatedRequest)
    private static final TopRatedRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TopRatedRequest();
    }

    public static TopRatedRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TopRatedRequest>
        PARSER = new com.google.protobuf.AbstractParser<TopRatedRequest>() {
      @Override
      public TopRatedRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TopRatedRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<TopRatedRequest> getParserForType() {
      return PARSER;
    }

    @Override
    public TopRatedRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TopRatedResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TopRatedResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Movie movie = 1;</code>
     */
    java.util.List<Movie>
        getMovieList();
    /**
     * <code>repeated .Movie movie = 1;</code>
     */
    Movie getMovie(int index);
    /**
     * <code>repeated .Movie movie = 1;</code>
     */
    int getMovieCount();
    /**
     * <code>repeated .Movie movie = 1;</code>
     */
    java.util.List<? extends MovieOrBuilder>
        getMovieOrBuilderList();
    /**
     * <code>repeated .Movie movie = 1;</code>
     */
    MovieOrBuilder getMovieOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code TopRatedResponse}
   */
  public static final class TopRatedResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TopRatedResponse)
      TopRatedResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TopRatedResponse.newBuilder() to construct.
    private TopRatedResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TopRatedResponse() {
      movie_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new TopRatedResponse();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GRPC.internal_static_TopRatedResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GRPC.internal_static_TopRatedResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TopRatedResponse.class, Builder.class);
    }

    public static final int MOVIE_FIELD_NUMBER = 1;
    private java.util.List<Movie> movie_;
    /**
     * <code>repeated .Movie movie = 1;</code>
     */
    @Override
    public java.util.List<Movie> getMovieList() {
      return movie_;
    }
    /**
     * <code>repeated .Movie movie = 1;</code>
     */
    @Override
    public java.util.List<? extends MovieOrBuilder>
        getMovieOrBuilderList() {
      return movie_;
    }
    /**
     * <code>repeated .Movie movie = 1;</code>
     */
    @Override
    public int getMovieCount() {
      return movie_.size();
    }
    /**
     * <code>repeated .Movie movie = 1;</code>
     */
    @Override
    public Movie getMovie(int index) {
      return movie_.get(index);
    }
    /**
     * <code>repeated .Movie movie = 1;</code>
     */
    @Override
    public MovieOrBuilder getMovieOrBuilder(
        int index) {
      return movie_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < movie_.size(); i++) {
        output.writeMessage(1, movie_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < movie_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, movie_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TopRatedResponse)) {
        return super.equals(obj);
      }
      TopRatedResponse other = (TopRatedResponse) obj;

      if (!getMovieList()
          .equals(other.getMovieList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getMovieCount() > 0) {
        hash = (37 * hash) + MOVIE_FIELD_NUMBER;
        hash = (53 * hash) + getMovieList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TopRatedResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TopRatedResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TopRatedResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TopRatedResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TopRatedResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TopRatedResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TopRatedResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TopRatedResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TopRatedResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TopRatedResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TopRatedResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TopRatedResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TopRatedResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TopRatedResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TopRatedResponse)
        TopRatedResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GRPC.internal_static_TopRatedResponse_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GRPC.internal_static_TopRatedResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TopRatedResponse.class, Builder.class);
      }

      // Construct using GRPC.TopRatedResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        if (movieBuilder_ == null) {
          movie_ = java.util.Collections.emptyList();
        } else {
          movie_ = null;
          movieBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GRPC.internal_static_TopRatedResponse_descriptor;
      }

      @Override
      public TopRatedResponse getDefaultInstanceForType() {
        return TopRatedResponse.getDefaultInstance();
      }

      @Override
      public TopRatedResponse build() {
        TopRatedResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public TopRatedResponse buildPartial() {
        TopRatedResponse result = new TopRatedResponse(this);
        int from_bitField0_ = bitField0_;
        if (movieBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            movie_ = java.util.Collections.unmodifiableList(movie_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.movie_ = movie_;
        } else {
          result.movie_ = movieBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TopRatedResponse) {
          return mergeFrom((TopRatedResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TopRatedResponse other) {
        if (other == TopRatedResponse.getDefaultInstance()) return this;
        if (movieBuilder_ == null) {
          if (!other.movie_.isEmpty()) {
            if (movie_.isEmpty()) {
              movie_ = other.movie_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMovieIsMutable();
              movie_.addAll(other.movie_);
            }
            onChanged();
          }
        } else {
          if (!other.movie_.isEmpty()) {
            if (movieBuilder_.isEmpty()) {
              movieBuilder_.dispose();
              movieBuilder_ = null;
              movie_ = other.movie_;
              bitField0_ = (bitField0_ & ~0x00000001);
              movieBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMovieFieldBuilder() : null;
            } else {
              movieBuilder_.addAllMessages(other.movie_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                Movie m =
                    input.readMessage(
                        Movie.parser(),
                        extensionRegistry);
                if (movieBuilder_ == null) {
                  ensureMovieIsMutable();
                  movie_.add(m);
                } else {
                  movieBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<Movie> movie_ =
        java.util.Collections.emptyList();
      private void ensureMovieIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          movie_ = new java.util.ArrayList<Movie>(movie_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Movie, Movie.Builder, MovieOrBuilder> movieBuilder_;

      /**
       * <code>repeated .Movie movie = 1;</code>
       */
      public java.util.List<Movie> getMovieList() {
        if (movieBuilder_ == null) {
          return java.util.Collections.unmodifiableList(movie_);
        } else {
          return movieBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Movie movie = 1;</code>
       */
      public int getMovieCount() {
        if (movieBuilder_ == null) {
          return movie_.size();
        } else {
          return movieBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Movie movie = 1;</code>
       */
      public Movie getMovie(int index) {
        if (movieBuilder_ == null) {
          return movie_.get(index);
        } else {
          return movieBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Movie movie = 1;</code>
       */
      public Builder setMovie(
          int index, Movie value) {
        if (movieBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMovieIsMutable();
          movie_.set(index, value);
          onChanged();
        } else {
          movieBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Movie movie = 1;</code>
       */
      public Builder setMovie(
          int index, Movie.Builder builderForValue) {
        if (movieBuilder_ == null) {
          ensureMovieIsMutable();
          movie_.set(index, builderForValue.build());
          onChanged();
        } else {
          movieBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Movie movie = 1;</code>
       */
      public Builder addMovie(Movie value) {
        if (movieBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMovieIsMutable();
          movie_.add(value);
          onChanged();
        } else {
          movieBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Movie movie = 1;</code>
       */
      public Builder addMovie(
          int index, Movie value) {
        if (movieBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMovieIsMutable();
          movie_.add(index, value);
          onChanged();
        } else {
          movieBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Movie movie = 1;</code>
       */
      public Builder addMovie(
          Movie.Builder builderForValue) {
        if (movieBuilder_ == null) {
          ensureMovieIsMutable();
          movie_.add(builderForValue.build());
          onChanged();
        } else {
          movieBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Movie movie = 1;</code>
       */
      public Builder addMovie(
          int index, Movie.Builder builderForValue) {
        if (movieBuilder_ == null) {
          ensureMovieIsMutable();
          movie_.add(index, builderForValue.build());
          onChanged();
        } else {
          movieBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Movie movie = 1;</code>
       */
      public Builder addAllMovie(
          Iterable<? extends Movie> values) {
        if (movieBuilder_ == null) {
          ensureMovieIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, movie_);
          onChanged();
        } else {
          movieBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Movie movie = 1;</code>
       */
      public Builder clearMovie() {
        if (movieBuilder_ == null) {
          movie_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          movieBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Movie movie = 1;</code>
       */
      public Builder removeMovie(int index) {
        if (movieBuilder_ == null) {
          ensureMovieIsMutable();
          movie_.remove(index);
          onChanged();
        } else {
          movieBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Movie movie = 1;</code>
       */
      public Movie.Builder getMovieBuilder(
          int index) {
        return getMovieFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Movie movie = 1;</code>
       */
      public MovieOrBuilder getMovieOrBuilder(
          int index) {
        if (movieBuilder_ == null) {
          return movie_.get(index);  } else {
          return movieBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Movie movie = 1;</code>
       */
      public java.util.List<? extends MovieOrBuilder>
           getMovieOrBuilderList() {
        if (movieBuilder_ != null) {
          return movieBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(movie_);
        }
      }
      /**
       * <code>repeated .Movie movie = 1;</code>
       */
      public Movie.Builder addMovieBuilder() {
        return getMovieFieldBuilder().addBuilder(
            Movie.getDefaultInstance());
      }
      /**
       * <code>repeated .Movie movie = 1;</code>
       */
      public Movie.Builder addMovieBuilder(
          int index) {
        return getMovieFieldBuilder().addBuilder(
            index, Movie.getDefaultInstance());
      }
      /**
       * <code>repeated .Movie movie = 1;</code>
       */
      public java.util.List<Movie.Builder>
           getMovieBuilderList() {
        return getMovieFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Movie, Movie.Builder, MovieOrBuilder>
          getMovieFieldBuilder() {
        if (movieBuilder_ == null) {
          movieBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Movie, Movie.Builder, MovieOrBuilder>(
                  movie_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          movie_ = null;
        }
        return movieBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TopRatedResponse)
    }

    // @@protoc_insertion_point(class_scope:TopRatedResponse)
    private static final TopRatedResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TopRatedResponse();
    }

    public static TopRatedResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TopRatedResponse>
        PARSER = new com.google.protobuf.AbstractParser<TopRatedResponse>() {
      @Override
      public TopRatedResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TopRatedResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<TopRatedResponse> getParserForType() {
      return PARSER;
    }

    @Override
    public TopRatedResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MovieOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Movie)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string movieId = 1;</code>
     * @return The movieId.
     */
    String getMovieId();
    /**
     * <code>string movieId = 1;</code>
     * @return The bytes for movieId.
     */
    com.google.protobuf.ByteString
        getMovieIdBytes();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string description = 3;</code>
     * @return The description.
     */
    String getDescription();
    /**
     * <code>string description = 3;</code>
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();
  }
  /**
   * Protobuf type {@code Movie}
   */
  public static final class Movie extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Movie)
      MovieOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Movie.newBuilder() to construct.
    private Movie(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Movie() {
      movieId_ = "";
      name_ = "";
      description_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Movie();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GRPC.internal_static_Movie_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GRPC.internal_static_Movie_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Movie.class, Builder.class);
    }

    public static final int MOVIEID_FIELD_NUMBER = 1;
    private volatile Object movieId_;
    /**
     * <code>string movieId = 1;</code>
     * @return The movieId.
     */
    @Override
    public String getMovieId() {
      Object ref = movieId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        movieId_ = s;
        return s;
      }
    }
    /**
     * <code>string movieId = 1;</code>
     * @return The bytes for movieId.
     */
    @Override
    public com.google.protobuf.ByteString
        getMovieIdBytes() {
      Object ref = movieId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        movieId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @Override
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 3;
    private volatile Object description_;
    /**
     * <code>string description = 3;</code>
     * @return The description.
     */
    @Override
    public String getDescription() {
      Object ref = description_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 3;</code>
     * @return The bytes for description.
     */
    @Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(movieId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, movieId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, description_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(movieId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, movieId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, description_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Movie)) {
        return super.equals(obj);
      }
      Movie other = (Movie) obj;

      if (!getMovieId()
          .equals(other.getMovieId())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getDescription()
          .equals(other.getDescription())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MOVIEID_FIELD_NUMBER;
      hash = (53 * hash) + getMovieId().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Movie parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Movie parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Movie parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Movie parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Movie parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Movie parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Movie parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Movie parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Movie parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Movie parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Movie parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Movie parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Movie prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Movie}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Movie)
        MovieOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GRPC.internal_static_Movie_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GRPC.internal_static_Movie_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Movie.class, Builder.class);
      }

      // Construct using GRPC.Movie.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        movieId_ = "";

        name_ = "";

        description_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GRPC.internal_static_Movie_descriptor;
      }

      @Override
      public Movie getDefaultInstanceForType() {
        return Movie.getDefaultInstance();
      }

      @Override
      public Movie build() {
        Movie result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Movie buildPartial() {
        Movie result = new Movie(this);
        result.movieId_ = movieId_;
        result.name_ = name_;
        result.description_ = description_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Movie) {
          return mergeFrom((Movie)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Movie other) {
        if (other == Movie.getDefaultInstance()) return this;
        if (!other.getMovieId().isEmpty()) {
          movieId_ = other.movieId_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                movieId_ = input.readStringRequireUtf8();

                break;
              } // case 10
              case 18: {
                name_ = input.readStringRequireUtf8();

                break;
              } // case 18
              case 26: {
                description_ = input.readStringRequireUtf8();

                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private Object movieId_ = "";
      /**
       * <code>string movieId = 1;</code>
       * @return The movieId.
       */
      public String getMovieId() {
        Object ref = movieId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          movieId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string movieId = 1;</code>
       * @return The bytes for movieId.
       */
      public com.google.protobuf.ByteString
          getMovieIdBytes() {
        Object ref = movieId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          movieId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string movieId = 1;</code>
       * @param value The movieId to set.
       * @return This builder for chaining.
       */
      public Builder setMovieId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        movieId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string movieId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMovieId() {
        
        movieId_ = getDefaultInstance().getMovieId();
        onChanged();
        return this;
      }
      /**
       * <code>string movieId = 1;</code>
       * @param value The bytes for movieId to set.
       * @return This builder for chaining.
       */
      public Builder setMovieIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        movieId_ = value;
        onChanged();
        return this;
      }

      private Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private Object description_ = "";
      /**
       * <code>string description = 3;</code>
       * @return The description.
       */
      public String getDescription() {
        Object ref = description_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string description = 3;</code>
       * @return The bytes for description.
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 3;</code>
       * @param value The description to set.
       * @return This builder for chaining.
       */
      public Builder setDescription(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescription() {
        
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>string description = 3;</code>
       * @param value The bytes for description to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        description_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Movie)
    }

    // @@protoc_insertion_point(class_scope:Movie)
    private static final Movie DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Movie();
    }

    public static Movie getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Movie>
        PARSER = new com.google.protobuf.AbstractParser<Movie>() {
      @Override
      public Movie parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Movie> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Movie> getParserForType() {
      return PARSER;
    }

    @Override
    public Movie getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TopRatedRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TopRatedRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TopRatedResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TopRatedResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Movie_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Movie_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\ngRPC.proto\"\021\n\017TopRatedRequest\")\n\020TopRa" +
      "tedResponse\022\025\n\005movie\030\001 \003(\0132\006.Movie\";\n\005Mo" +
      "vie\022\017\n\007movieId\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\023\n\013de" +
      "scription\030\003 \001(\t2M\n\017TopRatedService\022:\n\021Ge" +
      "tTopRatedMovies\022\020.TopRatedRequest\032\021.TopR" +
      "atedResponse\"\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_TopRatedRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TopRatedRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TopRatedRequest_descriptor,
        new String[] { });
    internal_static_TopRatedResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TopRatedResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TopRatedResponse_descriptor,
        new String[] { "Movie", });
    internal_static_Movie_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Movie_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Movie_descriptor,
        new String[] { "MovieId", "Name", "Description", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
