// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trending.proto
// Protobuf Java Version: 4.26.0-rc3

package com.example.newtrendingmoviesservice.protobuf;

public final class TrendingProto {
  private TrendingProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 0,
      /* suffix= */ "-rc3",
      TrendingProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TopMoviesRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.newtrendingmoviesservice.protobuf.TopMoviesRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code com.example.newtrendingmoviesservice.protobuf.TopMoviesRequest}
   */
  public static final class TopMoviesRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.example.newtrendingmoviesservice.protobuf.TopMoviesRequest)
      TopMoviesRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 0,
        /* suffix= */ "-rc3",
        TopMoviesRequest.class.getName());
    }
    // Use TopMoviesRequest.newBuilder() to construct.
    private TopMoviesRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private TopMoviesRequest() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.newtrendingmoviesservice.protobuf.TrendingProto.internal_static_com_example_newtrendingmoviesservice_protobuf_TopMoviesRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.newtrendingmoviesservice.protobuf.TrendingProto.internal_static_com_example_newtrendingmoviesservice_protobuf_TopMoviesRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesRequest.class, com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesRequest)) {
        return super.equals(obj);
      }
      com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesRequest other = (com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesRequest) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.example.newtrendingmoviesservice.protobuf.TopMoviesRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.newtrendingmoviesservice.protobuf.TopMoviesRequest)
        com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.newtrendingmoviesservice.protobuf.TrendingProto.internal_static_com_example_newtrendingmoviesservice_protobuf_TopMoviesRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.newtrendingmoviesservice.protobuf.TrendingProto.internal_static_com_example_newtrendingmoviesservice_protobuf_TopMoviesRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesRequest.class, com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesRequest.Builder.class);
      }

      // Construct using com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.newtrendingmoviesservice.protobuf.TrendingProto.internal_static_com_example_newtrendingmoviesservice_protobuf_TopMoviesRequest_descriptor;
      }

      @java.lang.Override
      public com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesRequest getDefaultInstanceForType() {
        return com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesRequest build() {
        com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesRequest buildPartial() {
        com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesRequest result = new com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesRequest(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesRequest) {
          return mergeFrom((com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesRequest other) {
        if (other == com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.example.newtrendingmoviesservice.protobuf.TopMoviesRequest)
    }

    // @@protoc_insertion_point(class_scope:com.example.newtrendingmoviesservice.protobuf.TopMoviesRequest)
    private static final com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesRequest();
    }

    public static com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TopMoviesRequest>
        PARSER = new com.google.protobuf.AbstractParser<TopMoviesRequest>() {
      @java.lang.Override
      public TopMoviesRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TopMoviesRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TopMoviesRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TopMoviesResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.newtrendingmoviesservice.protobuf.TopMoviesResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.example.newtrendingmoviesservice.protobuf.Movie top_movies = 1;</code>
     */
    java.util.List<com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie> 
        getTopMoviesList();
    /**
     * <code>repeated .com.example.newtrendingmoviesservice.protobuf.Movie top_movies = 1;</code>
     */
    com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie getTopMovies(int index);
    /**
     * <code>repeated .com.example.newtrendingmoviesservice.protobuf.Movie top_movies = 1;</code>
     */
    int getTopMoviesCount();
    /**
     * <code>repeated .com.example.newtrendingmoviesservice.protobuf.Movie top_movies = 1;</code>
     */
    java.util.List<? extends com.example.newtrendingmoviesservice.protobuf.TrendingProto.MovieOrBuilder> 
        getTopMoviesOrBuilderList();
    /**
     * <code>repeated .com.example.newtrendingmoviesservice.protobuf.Movie top_movies = 1;</code>
     */
    com.example.newtrendingmoviesservice.protobuf.TrendingProto.MovieOrBuilder getTopMoviesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.example.newtrendingmoviesservice.protobuf.TopMoviesResponse}
   */
  public static final class TopMoviesResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.example.newtrendingmoviesservice.protobuf.TopMoviesResponse)
      TopMoviesResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 0,
        /* suffix= */ "-rc3",
        TopMoviesResponse.class.getName());
    }
    // Use TopMoviesResponse.newBuilder() to construct.
    private TopMoviesResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private TopMoviesResponse() {
      topMovies_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.newtrendingmoviesservice.protobuf.TrendingProto.internal_static_com_example_newtrendingmoviesservice_protobuf_TopMoviesResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.newtrendingmoviesservice.protobuf.TrendingProto.internal_static_com_example_newtrendingmoviesservice_protobuf_TopMoviesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesResponse.class, com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesResponse.Builder.class);
    }

    public static final int TOP_MOVIES_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie> topMovies_;
    /**
     * <code>repeated .com.example.newtrendingmoviesservice.protobuf.Movie top_movies = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie> getTopMoviesList() {
      return topMovies_;
    }
    /**
     * <code>repeated .com.example.newtrendingmoviesservice.protobuf.Movie top_movies = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.example.newtrendingmoviesservice.protobuf.TrendingProto.MovieOrBuilder> 
        getTopMoviesOrBuilderList() {
      return topMovies_;
    }
    /**
     * <code>repeated .com.example.newtrendingmoviesservice.protobuf.Movie top_movies = 1;</code>
     */
    @java.lang.Override
    public int getTopMoviesCount() {
      return topMovies_.size();
    }
    /**
     * <code>repeated .com.example.newtrendingmoviesservice.protobuf.Movie top_movies = 1;</code>
     */
    @java.lang.Override
    public com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie getTopMovies(int index) {
      return topMovies_.get(index);
    }
    /**
     * <code>repeated .com.example.newtrendingmoviesservice.protobuf.Movie top_movies = 1;</code>
     */
    @java.lang.Override
    public com.example.newtrendingmoviesservice.protobuf.TrendingProto.MovieOrBuilder getTopMoviesOrBuilder(
        int index) {
      return topMovies_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < topMovies_.size(); i++) {
        output.writeMessage(1, topMovies_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < topMovies_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, topMovies_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesResponse)) {
        return super.equals(obj);
      }
      com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesResponse other = (com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesResponse) obj;

      if (!getTopMoviesList()
          .equals(other.getTopMoviesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getTopMoviesCount() > 0) {
        hash = (37 * hash) + TOP_MOVIES_FIELD_NUMBER;
        hash = (53 * hash) + getTopMoviesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.example.newtrendingmoviesservice.protobuf.TopMoviesResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.newtrendingmoviesservice.protobuf.TopMoviesResponse)
        com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.newtrendingmoviesservice.protobuf.TrendingProto.internal_static_com_example_newtrendingmoviesservice_protobuf_TopMoviesResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.newtrendingmoviesservice.protobuf.TrendingProto.internal_static_com_example_newtrendingmoviesservice_protobuf_TopMoviesResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesResponse.class, com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesResponse.Builder.class);
      }

      // Construct using com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (topMoviesBuilder_ == null) {
          topMovies_ = java.util.Collections.emptyList();
        } else {
          topMovies_ = null;
          topMoviesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.newtrendingmoviesservice.protobuf.TrendingProto.internal_static_com_example_newtrendingmoviesservice_protobuf_TopMoviesResponse_descriptor;
      }

      @java.lang.Override
      public com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesResponse getDefaultInstanceForType() {
        return com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesResponse build() {
        com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesResponse buildPartial() {
        com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesResponse result = new com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesResponse(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesResponse result) {
        if (topMoviesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            topMovies_ = java.util.Collections.unmodifiableList(topMovies_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.topMovies_ = topMovies_;
        } else {
          result.topMovies_ = topMoviesBuilder_.build();
        }
      }

      private void buildPartial0(com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesResponse result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesResponse) {
          return mergeFrom((com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesResponse other) {
        if (other == com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesResponse.getDefaultInstance()) return this;
        if (topMoviesBuilder_ == null) {
          if (!other.topMovies_.isEmpty()) {
            if (topMovies_.isEmpty()) {
              topMovies_ = other.topMovies_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureTopMoviesIsMutable();
              topMovies_.addAll(other.topMovies_);
            }
            onChanged();
          }
        } else {
          if (!other.topMovies_.isEmpty()) {
            if (topMoviesBuilder_.isEmpty()) {
              topMoviesBuilder_.dispose();
              topMoviesBuilder_ = null;
              topMovies_ = other.topMovies_;
              bitField0_ = (bitField0_ & ~0x00000001);
              topMoviesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getTopMoviesFieldBuilder() : null;
            } else {
              topMoviesBuilder_.addAllMessages(other.topMovies_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie m =
                    input.readMessage(
                        com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie.parser(),
                        extensionRegistry);
                if (topMoviesBuilder_ == null) {
                  ensureTopMoviesIsMutable();
                  topMovies_.add(m);
                } else {
                  topMoviesBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie> topMovies_ =
        java.util.Collections.emptyList();
      private void ensureTopMoviesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          topMovies_ = new java.util.ArrayList<com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie>(topMovies_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie, com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie.Builder, com.example.newtrendingmoviesservice.protobuf.TrendingProto.MovieOrBuilder> topMoviesBuilder_;

      /**
       * <code>repeated .com.example.newtrendingmoviesservice.protobuf.Movie top_movies = 1;</code>
       */
      public java.util.List<com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie> getTopMoviesList() {
        if (topMoviesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(topMovies_);
        } else {
          return topMoviesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.example.newtrendingmoviesservice.protobuf.Movie top_movies = 1;</code>
       */
      public int getTopMoviesCount() {
        if (topMoviesBuilder_ == null) {
          return topMovies_.size();
        } else {
          return topMoviesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.example.newtrendingmoviesservice.protobuf.Movie top_movies = 1;</code>
       */
      public com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie getTopMovies(int index) {
        if (topMoviesBuilder_ == null) {
          return topMovies_.get(index);
        } else {
          return topMoviesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.example.newtrendingmoviesservice.protobuf.Movie top_movies = 1;</code>
       */
      public Builder setTopMovies(
          int index, com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie value) {
        if (topMoviesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTopMoviesIsMutable();
          topMovies_.set(index, value);
          onChanged();
        } else {
          topMoviesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.example.newtrendingmoviesservice.protobuf.Movie top_movies = 1;</code>
       */
      public Builder setTopMovies(
          int index, com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie.Builder builderForValue) {
        if (topMoviesBuilder_ == null) {
          ensureTopMoviesIsMutable();
          topMovies_.set(index, builderForValue.build());
          onChanged();
        } else {
          topMoviesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.example.newtrendingmoviesservice.protobuf.Movie top_movies = 1;</code>
       */
      public Builder addTopMovies(com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie value) {
        if (topMoviesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTopMoviesIsMutable();
          topMovies_.add(value);
          onChanged();
        } else {
          topMoviesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.example.newtrendingmoviesservice.protobuf.Movie top_movies = 1;</code>
       */
      public Builder addTopMovies(
          int index, com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie value) {
        if (topMoviesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTopMoviesIsMutable();
          topMovies_.add(index, value);
          onChanged();
        } else {
          topMoviesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.example.newtrendingmoviesservice.protobuf.Movie top_movies = 1;</code>
       */
      public Builder addTopMovies(
          com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie.Builder builderForValue) {
        if (topMoviesBuilder_ == null) {
          ensureTopMoviesIsMutable();
          topMovies_.add(builderForValue.build());
          onChanged();
        } else {
          topMoviesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.example.newtrendingmoviesservice.protobuf.Movie top_movies = 1;</code>
       */
      public Builder addTopMovies(
          int index, com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie.Builder builderForValue) {
        if (topMoviesBuilder_ == null) {
          ensureTopMoviesIsMutable();
          topMovies_.add(index, builderForValue.build());
          onChanged();
        } else {
          topMoviesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.example.newtrendingmoviesservice.protobuf.Movie top_movies = 1;</code>
       */
      public Builder addAllTopMovies(
          java.lang.Iterable<? extends com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie> values) {
        if (topMoviesBuilder_ == null) {
          ensureTopMoviesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, topMovies_);
          onChanged();
        } else {
          topMoviesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.example.newtrendingmoviesservice.protobuf.Movie top_movies = 1;</code>
       */
      public Builder clearTopMovies() {
        if (topMoviesBuilder_ == null) {
          topMovies_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          topMoviesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.example.newtrendingmoviesservice.protobuf.Movie top_movies = 1;</code>
       */
      public Builder removeTopMovies(int index) {
        if (topMoviesBuilder_ == null) {
          ensureTopMoviesIsMutable();
          topMovies_.remove(index);
          onChanged();
        } else {
          topMoviesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.example.newtrendingmoviesservice.protobuf.Movie top_movies = 1;</code>
       */
      public com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie.Builder getTopMoviesBuilder(
          int index) {
        return getTopMoviesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.example.newtrendingmoviesservice.protobuf.Movie top_movies = 1;</code>
       */
      public com.example.newtrendingmoviesservice.protobuf.TrendingProto.MovieOrBuilder getTopMoviesOrBuilder(
          int index) {
        if (topMoviesBuilder_ == null) {
          return topMovies_.get(index);  } else {
          return topMoviesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.example.newtrendingmoviesservice.protobuf.Movie top_movies = 1;</code>
       */
      public java.util.List<? extends com.example.newtrendingmoviesservice.protobuf.TrendingProto.MovieOrBuilder> 
           getTopMoviesOrBuilderList() {
        if (topMoviesBuilder_ != null) {
          return topMoviesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(topMovies_);
        }
      }
      /**
       * <code>repeated .com.example.newtrendingmoviesservice.protobuf.Movie top_movies = 1;</code>
       */
      public com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie.Builder addTopMoviesBuilder() {
        return getTopMoviesFieldBuilder().addBuilder(
            com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie.getDefaultInstance());
      }
      /**
       * <code>repeated .com.example.newtrendingmoviesservice.protobuf.Movie top_movies = 1;</code>
       */
      public com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie.Builder addTopMoviesBuilder(
          int index) {
        return getTopMoviesFieldBuilder().addBuilder(
            index, com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie.getDefaultInstance());
      }
      /**
       * <code>repeated .com.example.newtrendingmoviesservice.protobuf.Movie top_movies = 1;</code>
       */
      public java.util.List<com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie.Builder> 
           getTopMoviesBuilderList() {
        return getTopMoviesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie, com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie.Builder, com.example.newtrendingmoviesservice.protobuf.TrendingProto.MovieOrBuilder> 
          getTopMoviesFieldBuilder() {
        if (topMoviesBuilder_ == null) {
          topMoviesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie, com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie.Builder, com.example.newtrendingmoviesservice.protobuf.TrendingProto.MovieOrBuilder>(
                  topMovies_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          topMovies_ = null;
        }
        return topMoviesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.example.newtrendingmoviesservice.protobuf.TopMoviesResponse)
    }

    // @@protoc_insertion_point(class_scope:com.example.newtrendingmoviesservice.protobuf.TopMoviesResponse)
    private static final com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesResponse();
    }

    public static com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TopMoviesResponse>
        PARSER = new com.google.protobuf.AbstractParser<TopMoviesResponse>() {
      @java.lang.Override
      public TopMoviesResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TopMoviesResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TopMoviesResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.newtrendingmoviesservice.protobuf.TrendingProto.TopMoviesResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MovieOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.newtrendingmoviesservice.protobuf.Movie)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string movieId = 1;</code>
     * @return The movieId.
     */
    java.lang.String getMovieId();
    /**
     * <code>string movieId = 1;</code>
     * @return The bytes for movieId.
     */
    com.google.protobuf.ByteString
        getMovieIdBytes();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string description = 3;</code>
     * @return The description.
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 3;</code>
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();
  }
  /**
   * Protobuf type {@code com.example.newtrendingmoviesservice.protobuf.Movie}
   */
  public static final class Movie extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.example.newtrendingmoviesservice.protobuf.Movie)
      MovieOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 0,
        /* suffix= */ "-rc3",
        Movie.class.getName());
    }
    // Use Movie.newBuilder() to construct.
    private Movie(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Movie() {
      movieId_ = "";
      name_ = "";
      description_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.newtrendingmoviesservice.protobuf.TrendingProto.internal_static_com_example_newtrendingmoviesservice_protobuf_Movie_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.newtrendingmoviesservice.protobuf.TrendingProto.internal_static_com_example_newtrendingmoviesservice_protobuf_Movie_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie.class, com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie.Builder.class);
    }

    public static final int MOVIEID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object movieId_ = "";
    /**
     * <code>string movieId = 1;</code>
     * @return The movieId.
     */
    @java.lang.Override
    public java.lang.String getMovieId() {
      java.lang.Object ref = movieId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        movieId_ = s;
        return s;
      }
    }
    /**
     * <code>string movieId = 1;</code>
     * @return The bytes for movieId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMovieIdBytes() {
      java.lang.Object ref = movieId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        movieId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object description_ = "";
    /**
     * <code>string description = 3;</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 3;</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(movieId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, movieId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, description_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(movieId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, movieId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, description_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie)) {
        return super.equals(obj);
      }
      com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie other = (com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie) obj;

      if (!getMovieId()
          .equals(other.getMovieId())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getDescription()
          .equals(other.getDescription())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MOVIEID_FIELD_NUMBER;
      hash = (53 * hash) + getMovieId().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.example.newtrendingmoviesservice.protobuf.Movie}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.newtrendingmoviesservice.protobuf.Movie)
        com.example.newtrendingmoviesservice.protobuf.TrendingProto.MovieOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.newtrendingmoviesservice.protobuf.TrendingProto.internal_static_com_example_newtrendingmoviesservice_protobuf_Movie_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.newtrendingmoviesservice.protobuf.TrendingProto.internal_static_com_example_newtrendingmoviesservice_protobuf_Movie_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie.class, com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie.Builder.class);
      }

      // Construct using com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        movieId_ = "";
        name_ = "";
        description_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.newtrendingmoviesservice.protobuf.TrendingProto.internal_static_com_example_newtrendingmoviesservice_protobuf_Movie_descriptor;
      }

      @java.lang.Override
      public com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie getDefaultInstanceForType() {
        return com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie build() {
        com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie buildPartial() {
        com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie result = new com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.movieId_ = movieId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.description_ = description_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie) {
          return mergeFrom((com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie other) {
        if (other == com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie.getDefaultInstance()) return this;
        if (!other.getMovieId().isEmpty()) {
          movieId_ = other.movieId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                movieId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                description_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object movieId_ = "";
      /**
       * <code>string movieId = 1;</code>
       * @return The movieId.
       */
      public java.lang.String getMovieId() {
        java.lang.Object ref = movieId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          movieId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string movieId = 1;</code>
       * @return The bytes for movieId.
       */
      public com.google.protobuf.ByteString
          getMovieIdBytes() {
        java.lang.Object ref = movieId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          movieId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string movieId = 1;</code>
       * @param value The movieId to set.
       * @return This builder for chaining.
       */
      public Builder setMovieId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        movieId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string movieId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMovieId() {
        movieId_ = getDefaultInstance().getMovieId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string movieId = 1;</code>
       * @param value The bytes for movieId to set.
       * @return This builder for chaining.
       */
      public Builder setMovieIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        movieId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string description = 3;</code>
       * @return The description.
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description = 3;</code>
       * @return The bytes for description.
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 3;</code>
       * @param value The description to set.
       * @return This builder for chaining.
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        description_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescription() {
        description_ = getDefaultInstance().getDescription();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string description = 3;</code>
       * @param value The bytes for description to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        description_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.example.newtrendingmoviesservice.protobuf.Movie)
    }

    // @@protoc_insertion_point(class_scope:com.example.newtrendingmoviesservice.protobuf.Movie)
    private static final com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie();
    }

    public static com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Movie>
        PARSER = new com.google.protobuf.AbstractParser<Movie>() {
      @java.lang.Override
      public Movie parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Movie> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Movie> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.newtrendingmoviesservice.protobuf.TrendingProto.Movie getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_newtrendingmoviesservice_protobuf_TopMoviesRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_newtrendingmoviesservice_protobuf_TopMoviesRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_newtrendingmoviesservice_protobuf_TopMoviesResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_newtrendingmoviesservice_protobuf_TopMoviesResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_newtrendingmoviesservice_protobuf_Movie_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_newtrendingmoviesservice_protobuf_Movie_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016trending.proto\022-com.example.newtrendin" +
      "gmoviesservice.protobuf\"\022\n\020TopMoviesRequ" +
      "est\"]\n\021TopMoviesResponse\022H\n\ntop_movies\030\001" +
      " \003(\01324.com.example.newtrendingmoviesserv" +
      "ice.protobuf.Movie\";\n\005Movie\022\017\n\007movieId\030\001" +
      " \001(\t\022\014\n\004name\030\002 \001(\t\022\023\n\013description\030\003 \001(\t2" +
      "\263\001\n\025TrendingMoviesService\022\231\001\n\024GetTopMovi" +
      "esByRating\022?.com.example.newtrendingmovi" +
      "esservice.protobuf.TopMoviesRequest\032@.co" +
      "m.example.newtrendingmoviesservice.proto" +
      "buf.TopMoviesResponseB>\n-com.example.new" +
      "trendingmoviesservice.protobufB\rTrending" +
      "Protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_newtrendingmoviesservice_protobuf_TopMoviesRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_newtrendingmoviesservice_protobuf_TopMoviesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_newtrendingmoviesservice_protobuf_TopMoviesRequest_descriptor,
        new java.lang.String[] { });
    internal_static_com_example_newtrendingmoviesservice_protobuf_TopMoviesResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_newtrendingmoviesservice_protobuf_TopMoviesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_newtrendingmoviesservice_protobuf_TopMoviesResponse_descriptor,
        new java.lang.String[] { "TopMovies", });
    internal_static_com_example_newtrendingmoviesservice_protobuf_Movie_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_example_newtrendingmoviesservice_protobuf_Movie_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_newtrendingmoviesservice_protobuf_Movie_descriptor,
        new java.lang.String[] { "MovieId", "Name", "Description", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
